# To start all app containers and have them talking to each other, in the
# root folder /, run 'docker-compose up'.
# Refer to /README.md for more information.

# Docker Compose File Format Version.
# version: "3.7"

services:
  server:
    build:
      context: ./server
    volumes:
      - ./server:/app
      - /app/node_modules # Required to persist node_modules between container stop/starts.
    ports:
      - 5000:5000
    env_file: ./server/.env

  client:
    build:
      context: ./client
    # This will force server service to build and start before client.
    depends_on:
      - server
    # THIS IS FOR CONNECTING THE DOCKER TO LOCAL DEV AND CAUSED THE WEIRD HTML WRONG FILE ISSUE
    #volumes:
    #  - ./client:/home/static
    #  - /app/node_modules # Required to persist node_modules between container stop/starts.
    ports:
      - 8080:8080
    environment:
      CHOKIDAR_USEPOLLING: "true"