# To start all app containers and have them talking to each other, in the
# root folder /, run 'docker-compose up'.
# Refer to /README.md for more information.

#
#
#
# SHOULD REPLACE ENV WITH SECRETS
# https://docs.docker.com/compose/how-tos/use-secrets/
#
#
services:
  server:
    build:
      context: ./server
    # volumes - Allows the data in the volumes to persist between docker sessions
    volumes:
      - /app/node_modules
    ports:
      - 5000:5000
    #env_file: ./server/.env
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - CLIENT_URL=${CLIENT_URL}
      - BACKEND_URL=${BACKEND_URL}
      - SESSION_SECRET=${SESSION_SECRET}

  client:
    build:
      context: ./client
    # This will force server service to build and start before client.
    depends_on:
      - server
    # volumes - Allows the data in the volumes to persist between docker sessions
    volumes:
      - /app/node_modules
    ports:
      - 8080:8080
    environment:
      CHOKIDAR_USEPOLLING: "true"
